"""
Prompt templates for the Planner / Collector / Writer pipeline.

We ship two complete sets:

  * BASELINE  — verbose, instruction-heavy prompts. Representative of
    a typical first-draft prompt engineering pass.
  * OPTIMIZED — same intent, compressed: bullet-form structure, fewer
    examples, explicit "be concise" output controls.

These are the two ends of the comparison. The point of the reference
app is to *measure* the SCI delta between them.

Both sets cover Green Software Foundation pillars (Energy Efficiency,
Hardware Efficiency, Carbon Awareness) for sustainability analyses.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PromptSet:
    """A complete set of prompts for the three-phase pipeline."""
    name: str
    planner: str
    collector: str
    writer: str


# ----------------------------------------------------------------------
# BASELINE — verbose, example-heavy. Don't ship this to production.
# ----------------------------------------------------------------------
_BASELINE_PLANNER = """\
You are a Green Software Foundation (GSF) expert specializing in sustainable \
software development. Create a comprehensive sustainability analysis plan \
for the user's query.

User query: "{query}"

Produce a plan with the following components:

1. Core Sustainability Challenge — reframe the query around the three GSF \
pillars (Energy Efficiency, Hardware Efficiency, Carbon Awareness) and \
explicitly prioritise the pillar(s) with the greatest potential impact. \
Explain the reasoning behind your prioritisation.

2. Key Investigation Areas — develop 6 to 8 critical questions across \
algorithmic optimisation, runtime efficiency, hardware utilisation, \
resource scaling, carbon-aware execution, measurement and monitoring, \
framework or language specifics, and cloud-versus-edge deployment.

3. Technical Research Sources — list 8 to 10 specific tools, frameworks, \
publications, and search keywords to investigate.

4. Implementation Framework — cover immediate optimisations (quick wins \
with examples), measurement baselines (specific tools and metrics), \
infrastructure changes, longer-term architectural changes, and \
continuous monitoring practices.

For each recommendation discuss the performance-versus-cost-versus-\
sustainability trade-off. Make every item actionable. Provide concrete \
examples wherever possible. Use markdown headings and bullets.\
"""

_BASELINE_COLLECTOR = """\
Research sustainable software techniques based on the following plan:

{plan}

Produce detailed insights covering, with sources for every claim:

- Sustainability reporting for any named tools, products, or organisations
- Environmental and carbon-impact data with measured figures where available
- Optimisation strategies and tools with code examples
- Hardware efficiency and lifecycle considerations
- Performance-versus-energy trade-offs with quantitative evidence
- Case studies and published sustainability reports
- Data-consumption best practices

Source-quality requirements:
- Cite every fact with a URL or full bibliographic reference
- State "No public information found" explicitly when data is unavailable
- Present all viewpoints fairly when sources conflict
- Mark inferences from general knowledge as inferences

Format the response with markdown headings, bullets, and fenced code blocks.\
"""

_BASELINE_WRITER = """\
Create a comprehensive technical sustainability report drawing directly \
from the supplied plan and research.

Plan:
{plan}

Research:
{insights}

Structure the report with the following sections in this order. For each \
section, draw concrete examples and metrics from the research above.

## Energy Efficiency Strategies
Most impactful energy optimisation techniques. Include before/after code \
patterns and references to energy-profiling tools with installation commands.

## Hardware Resource Optimization
Memory, CPU, network, and storage optimisation. Include specific libraries \
and configuration examples.

## Carbon-Aware Computing Practices
Workload scheduling, carbon-intensity monitoring, batch-processing aligned \
with renewable availability, regional deployment guidelines, and \
carbon-calculation methodologies.

## Trade-Offs and Practical Considerations
Performance-versus-energy trade-offs with examples and real-world challenges \
in implementing the recommendations.

## Implementation Roadmap
Immediate actions, measurement baselines, medium-term architectural \
improvements, and continuous monitoring practices.

## Conclusion
Summary of key findings and concrete next steps.

Disclaimer: this report is generated by an AI system for educational purposes; \
verify independently before production use.\
"""

BASELINE = PromptSet(
    name="baseline",
    planner=_BASELINE_PLANNER,
    collector=_BASELINE_COLLECTOR,
    writer=_BASELINE_WRITER,
)


# ----------------------------------------------------------------------
# OPTIMIZED — same coverage, ~60–70% shorter, explicit output controls.
# ----------------------------------------------------------------------
_OPTIMIZED_PLANNER = """\
GSF expert. Sustainability plan for: "{query}"

Output: bullets only, no preamble, no repetition.

1. GSF pillars: which to prioritise (energy / hardware / carbon-aware) and why.
2. 6-8 investigation questions across: algorithms, runtime, hardware, \
scaling, carbon-aware execution, measurement, framework specifics, \
cloud-vs-edge.
3. 8-10 specific tools, frameworks, or sources.
4. Implementation: quick wins, measurement baseline, infra changes, \
long-term architecture, monitoring.

Note trade-offs. Be concise.\
"""

_OPTIMIZED_COLLECTOR = """\
Research sustainable-software techniques for plan:
{plan}

Output: bullets, with source for every claim. Cover:
- Sustainability reporting for named entities
- Carbon-impact data (measured where possible)
- Optimisation strategies & tools (brief code only)
- Hardware efficiency & lifecycle
- Perf-vs-energy trade-offs (quantitative)
- Case studies
- Data-consumption practices

Rules: cite or say "No public info"; flag inferences; markdown + fenced code.\
"""

_OPTIMIZED_WRITER = """\
Technical sustainability report from Plan and Research below.

Plan:
{plan}

Research:
{insights}

Output: bullets only, concise. Sections in order:

## Energy Efficiency Strategies
## Hardware Resource Optimization
## Carbon-Aware Computing Practices
## Trade-Offs and Practical Considerations
## Implementation Roadmap
## Conclusion

Draw directly from plan & research. Include code only where it adds value. \
No filler.\
"""

OPTIMIZED = PromptSet(
    name="optimized",
    planner=_OPTIMIZED_PLANNER,
    collector=_OPTIMIZED_COLLECTOR,
    writer=_OPTIMIZED_WRITER,
)


# ----------------------------------------------------------------------
# Registry — extend with your own variants for A/B testing.
# ----------------------------------------------------------------------
PROMPT_SETS: dict[str, PromptSet] = {
    "baseline": BASELINE,
    "optimized": OPTIMIZED,
}
